blank_issues_enabled: false
contact_links:
  - name: "\U000026A0 Feature request"
    url: https://github.com/Tyrrrz/LightBulb/wiki/Maintenance-mode
    about: Sorry, but this project is in maintenance mode and no longer accepts new feature requests.
  - name: "\U0001F4D6 Read the wiki"
    url: https://github.com/Tyrrrz/LightBulb/wiki
    about: Find answers to most common questions.
  - name: "\U0001F5E8 Ask a question"
    url: https://github.com/Tyrrrz/LightBulb/discussions/new
    about: Please ask and answer questions here.