name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: 3.1.100

    - name: Build & test
      run: dotnet test -c Release -l GitHubActions

    - name: Build & publish
      run: dotnet publish LightBulb/ -o LightBulb/bin/Publish/ -c Release -r win-x86 --self-contained false

    - name: Create installer
      run: |
        choco install innosetup --no-progress
        Copy-Item -Path LightBulb/bin/Publish/ -Recurse -Destination Installer/Source/
        & "c:\Program Files (x86)\Inno Setup 6\ISCC.exe" Installer/Installer.iss
      shell: pwsh

    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: LightBulb
        path: LightBulb/bin/Publish/

    - name: Upload build artifact (installer)
      uses: actions/upload-artifact@v1
      with:
        name: LightBulb-Installer
        path: Installer/bin/LightBulb-Installer.exe
