name: main

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest
    permissions:
      contents: read

    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Run tests
        run: >
          dotnet test
          --configuration Release
          --logger "GitHubActions;summary.includePassedTests=true;summary.includeSkippedTests=true"
          --collect:"XPlat Code Coverage"
          --
          DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  pack:
    needs: test
    runs-on: windows-latest
    permissions:
      actions: write
      contents: read

    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Publish
        run: >
          dotnet publish LightBulb
          --output LightBulb/bin/publish/
          --configuration Release

      - name: Create installer
        shell: pwsh
        run: |
          choco install innosetup --no-progress
          Copy-Item -Path LightBulb/bin/publish/ -Recurse -Destination Installer/Source/
          & "c:\Program Files (x86)\Inno Setup 6\ISCC.exe" Installer/Installer.iss

      - name: Upload artifacts (portable)
        uses: actions/upload-artifact@v3
        with:
          name: LightBulb
          path: LightBulb/bin/publish/

      - name: Upload artifacts (installer)
        uses: actions/upload-artifact@v3
        with:
          name: LightBulb-Installer
          path: Installer/bin/LightBulb-Installer.exe

  deploy:
    if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
    needs: pack
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write

    steps:
      - name: Download artifacts (portable)
        uses: actions/download-artifact@v3
        with:
          name: LightBulb
          path: LightBulb

      - name: Download artifacts (installer)
        uses: actions/download-artifact@v3
        with:
          name: LightBulb-Installer

      - name: Create package (portable)
        shell: pwsh
        run: >
          Compress-Archive
          -Path LightBulb/*
          -DestinationPath LightBulb.zip
          -Force

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          gh release create ${{ github.ref_name }} LightBulb.zip LightBulb-Installer.exe
          --title ${{ github.ref_name }}
          --notes "[Changelog](https://github.com/Tyrrrz/LightBulb/blob/master/Changelog.md)"
          --verify-tag

  notify:
    needs: deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Notify Discord
        uses: tyrrrz/action-http-request@v1
        with:
          url: ${{ secrets.DISCORD_WEBHOOK }}
          method: POST
          headers: |
            Content-Type: application/json; charset=UTF-8
          body: |
            {
              "content": "**LightBulb** new version released!\nVersion: `${{ github.ref_name }}`\nChangelog: <https://github.com/Tyrrrz/LightBulb/blob/${{ github.ref_name }}/Changelog.md>"
            }